### ISSUE TITLE
How to run this ?

### ISSUE THREAD

**Issue by mlotfi2005** [machzqcq/docker-for-all#2]
Hi,

I am new intesting, I found your github, it has lot of good things, but too much for me, I just want to create a grid setup in my windows 7 with Docker container and Jenkins to test cucumber features, I am using ruby scripts, please could you help me, you said :+1: 

Instructions to use
Checkout the project (git clone <repo_url>)
Run bundle install
Go through .feature files
Check step defnition

But how to run it ?
Thanks.

**Comment by machzqcq** [comment]
Hi there,
Sorry for the late response. It is assumed that you know how to run ruby cucumber features. This repo is focused on teaching docker and it is very difficult to write documentation for out of scope (outside of docker) to write up. Alternately, if you had tried looking up online and then asked specific questions through email, we might be able to help. 

Thanks !
